all: Comanda
Comanda: Modulo-Comanda/src/Modulo-Comanda.c Conexion-Serializacion/utils.c Conexion-Serializacion/serializacion.c 
	gcc Modulo-Comanda/src/Modulo-Comanda.c Conexion-Serializacion/utils.c Conexion-Serializacion/serializacion.c -o Comanda -lcommons -lpthread
